# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Phyzmo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Phyzmo

pod 'Firebase/Analytics'
pod 'FirebaseAuth'
pod 'FirebaseDatabase'
pod 'Firebase/Storage'
pod 'Charts'

  target 'PhyzmoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhyzmoUITests' do
    # Pods for testing
  end

end
